# Generated by Django 2.2 on 2019-04-18 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_auto_20190419_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_rating',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Comment'),
        ),
        migrations.AlterField(
            model_name='post_rating',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Post'),
        ),
    ]
